name: Prueba numero 1

on:
  push:
    branches:
      - main

jobs:
  decir-hola:
    runs-on: ubuntu-latest

    steps:
      - name: mostrar mensaje
        run: echo "Hola Mundo"
      - name: Enviar Petición
        run: |
          curl -X POST 'https://webhook.site/892f2749-aba3-44c8-af63-04640edf7a85' \
          -H 'content-type: application/json' \
          -d '{"nombre": "Vargas"}'
